#!/usr/bin/env python3
"""Launch independent VP Scalp Grid robot instances.
Each instance: own directory, own config.py, symlinks to source .py files.
Does NOT touch the main robot (port 5070, SiM6).

Usage:
  python3 launcher.py create <instance_dir> <port> <ticker> [params_json]
  python3 launcher.py start   <instance_dir> <port>
  python3 launcher.py stop    <instance_dir>
  python3 launcher.py status  <instance_dir>
"""
import sys, os, json, subprocess, signal, shutil

# Debug log
DEBUG_LOG = '/tmp/launcher_debug.log'
def _log(msg):
    with open(DEBUG_LOG, 'a') as f:
        f.write(f'{msg}\n')

_log(f'launcher.py called: argv={sys.argv}')

ROBOT_SRC = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'robot'))
INSTANCE_BASE = os.path.abspath(os.path.dirname(__file__))

TICKER_SYMBOL_MAP = {
    'SiM6': 'SiM6@RTSX', 'SiU6': 'SiU6@RTSX', 'SiH7': 'SiH7@RTSX',
    'MXM6': 'MXM6@RTSX', 'MXU6': 'MXU6@RTSX',
    'GDM6': 'GDM6@RTSX', 'BRK6': 'BRK6@RTSX',
    'RIM6': 'RIM6@RTSX', 'RIU6': 'RIU6@RTSX',
}

# Files that should be COPIED (instance-specific)
COPY_FILES = {'config.py'}

# Files that should be SYMLINKED (shared code)
SYMLINK_FILES = {
    'main.py', 'api.py', 'feed.py', 'strategy.py', 'vp.py',
    'orders.py', 'orders_dp.py', 'orders_grpc.py', 'risk.py', 'state.py',
}


def create(instance_dir, port, ticker, params_json='{}'):
    """Create instance directory with config.py and symlinks."""
    os.makedirs(instance_dir, exist_ok=True)

    # Clean old state/pid/logs
    for f in ['state.json', 'pid', 'stdout.log', 'stderr.log', 'strategy.json']:
        fp = os.path.join(instance_dir, f)
        if os.path.exists(fp):
            os.remove(fp)

    # Remove old symlinks/copies
    for f in os.listdir(instance_dir):
        fp = os.path.join(instance_dir, f)
        if os.path.islink(fp) or f.endswith('.py'):
            if os.path.islink(fp):
                os.remove(fp)
            elif f in COPY_FILES:
                os.remove(fp)

    # Create symlinks for shared code
    for fname in SYMLINK_FILES:
        src = os.path.join(ROBOT_SRC, fname)
        dst = os.path.join(instance_dir, fname)
        if os.path.exists(src) and not os.path.exists(dst):
            os.symlink(src, dst)

    # Write instance-specific config.py
    symbol = TICKER_SYMBOL_MAP.get(ticker, ticker + '@RTSX')
    # Read params from instance_params.json (written by C#) or from argument
    params_file = os.path.join(instance_dir, 'instance_params.json')
    if os.path.exists(params_file):
        with open(params_file) as f:
            params = json.load(f)
        _log(f'Params from file: {params}')
    else:
        try:
            params = json.loads(params_json) if isinstance(params_json, str) else params_json
        except json.JSONDecodeError:
            _log(f'Failed to parse params: {params_json}')
            params = {}

    config_content = f'''"""Instance config — auto-generated by launcher."""
import os

# Finam credentials
FINAM_TOKEN = os.environ.get("FINAM_TOKEN", "")
FINAM_API_KEY = os.environ.get("FINAM_API_KEY", "")
FINAM_ACCOUNT_ID = os.environ.get("FINAM_ACCOUNT_ID", "1225953")

# Trading parameters
SYMBOL = "{symbol}"
TICKER = "{ticker}"
TIMEFRAME = "{params.get('timeframe', 'M1')}"

# gRPC reconnect
GRPC_RECONNECT_SEC = 5

# Warmup candles (REST)
WARMUP_BARS = 120

# API port
API_PORT = {port}
'''
    config_path = os.path.join(instance_dir, 'config.py')
    with open(config_path, 'w') as f:
        f.write(config_content)

    # Write strategy config (robot reads from strategy.json in cwd)
    strat_cfg = {
        'max_levels': params.get('max_levels', 100),
        'step_base': params.get('step_base', 20),
        'spread_base': params.get('spread_base', 33),
        'max_hold_minutes': params.get('max_hold_minutes', 99999999999999),
        'min_profit_per_lot': params.get('min_profit_per_lot', 50),
        'vp_lookback': params.get('vp_lookback', 30),
        'vp_bin_size': params.get('vp_bin_size', 50),
        'vp_va_percent': params.get('vp_va_percent', 0.70),
        'rv_adaptation': params.get('rv_adaptation', False),
    }
    with open(os.path.join(instance_dir, 'strategy.json'), 'w') as f:
        json.dump(strat_cfg, f, indent=2)

    print(json.dumps({
        'created': True,
        'dir': instance_dir,
        'port': port,
        'ticker': ticker,
        'symbol': symbol,
    }))


def start(instance_dir, port):
    """Start robot process in instance directory."""
    pid_file = os.path.join(instance_dir, 'pid')

    # Check if already running
    if os.path.exists(pid_file):
        with open(pid_file) as f:
            old_pid = int(f.read().strip())
        try:
            os.kill(old_pid, 0)
            print(json.dumps({'error': f'Already running (pid={old_pid})'}))
            return
        except ProcessLookupError:
            os.remove(pid_file)

    # Check port not in use
    import socket
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    result = sock.connect_ex(('127.0.0.1', port))
    sock.close()
    if result == 0:
        print(json.dumps({'error': f'Port {port} already in use'}))
        return

    # Read config to get API_PORT
    main_py = os.path.join(instance_dir, 'main.py')
    if not os.path.exists(main_py):
        print(json.dumps({'error': 'main.py not found — run create first'}))
        return

    # Launch main.py with cwd = instance_dir
    # This way main.py imports local config.py first
    proc = subprocess.Popen(
        [sys.executable, 'main.py'],
        cwd=instance_dir,
        env=os.environ.copy(),
        stdout=open(os.path.join(instance_dir, 'stdout.log'), 'a'),
        stderr=open(os.path.join(instance_dir, 'stderr.log'), 'a'),
    )

    with open(pid_file, 'w') as f:
        f.write(str(proc.pid))

    print(json.dumps({
        'started': True,
        'pid': proc.pid,
        'port': port,
        'dir': instance_dir,
    }))


def stop(instance_dir, port=0):
    """Stop robot — first call /stop API, then kill process."""
    pid_file = os.path.join(instance_dir, 'pid')
    
    # Try graceful stop via API
    if port > 0:
        import urllib.request
        try:
            req = urllib.request.Request(f'http://127.0.0.1:{port}/stop', method='POST')
            urllib.request.urlopen(req, timeout=5)
            import time; time.sleep(2)
        except:
            pass

    # Kill by port
    if port > 0:
        try:
            subprocess.run(['fuser', '-k', f'{port}/tcp'], capture_output=True, timeout=3)
        except:
            pass

    # Kill by pid
    if os.path.exists(pid_file):
        with open(pid_file) as f:
            pid = int(f.read().strip())
        try:
            os.kill(pid, signal.SIGTERM)
        except ProcessLookupError:
            pass
        os.remove(pid_file)

    print(json.dumps({'stopped': True, 'dir': instance_dir}))


def status(instance_dir):
    """Check if instance is running."""
    pid_file = os.path.join(instance_dir, 'pid')
    if not os.path.exists(pid_file):
        print(json.dumps({'status': 'stopped'}))
        return
    with open(pid_file) as f:
        pid = int(f.read().strip())
    try:
        os.kill(pid, 0)
        print(json.dumps({'status': 'running', 'pid': pid}))
    except ProcessLookupError:
        print(json.dumps({'status': 'stopped (stale pid)'}))


if __name__ == '__main__':
    if len(sys.argv) < 3:
        print("Usage:")
        print("  launcher.py create <dir> <port> <ticker> [params_json]")
        print("  launcher.py start   <dir> <port>")
        print("  launcher.py stop    <dir> [port]")
        print("  launcher.py status  <dir>")
        sys.exit(1)

    cmd = sys.argv[1]
    if cmd == 'create':
        params = sys.argv[5] if len(sys.argv) > 5 else '{}'
        create(sys.argv[2], int(sys.argv[3]), sys.argv[4], params)
    elif cmd == 'start':
        start(sys.argv[2], int(sys.argv[3]))
    elif cmd == 'stop':
        port = int(sys.argv[3]) if len(sys.argv) > 3 else 0
        stop(sys.argv[2], port)
    elif cmd == 'status':
        status(sys.argv[2])
