<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>HedgeFund.Core</RootNamespace>
  </PropertyGroup>

  <!-- StockSharp для аналитики (индикаторы) -->
  <ItemGroup>
    <PackageReference Include="StockSharp.Algo" Version="5.0.222" />
    <PackageReference Include="StockSharp.Messages" Version="5.0.222" />
  </ItemGroup>

</Project>
